import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/Navbar';
import { poppins, bebasNeue, montserrat } from '@/lib/fonts';
import { SmoothScrolling } from '@/utils/SmoothScrolling';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${montserrat.variable} ${bebasNeue.variable} bg-white pt-24`}
    >
      <SmoothScrolling />
      <body className="flex min-h-screen justify-center">
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
